{
 "title": "Local Weather",
 "time": { "from": "now", "to": "now+24h" },
 "refresh": "5m",
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indoor Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_listener_v2",
     "query": "SELECT (mean(\"tempinf\") - 32) * 5 / 9 FROM \"http_listener_v2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "tempinf" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " ( - 32) / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Indoor Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_listener_v2",
     "select": [
      [
       { "params": [ "humidityin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Outdoor Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_listener_v2",
     "select": [
      [
       { "params": [ "humidity1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outdoor Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_listener_v2",
     "query": "SELECT (mean(\"temp1f\") - 32) * 5 / 9 FROM \"http_listener_v2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "tempinf" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " ( - 32) / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sunrise & Sunset",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Date & time" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "sunrise" ], "type": "field" },
       { "params": [ " / 1000 /1000" ], "type": "math" },
       { "params": [ "Sunrise" ], "type": "alias" }
      ],
      [
       { "params": [ "sunset" ], "type": "field" },
       { "params": [ " / 1000 /1000" ], "type": "math" },
       { "params": [ "Sunset" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "3h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_listener_v2",
     "select": [
      [
       { "params": [ "baromabsin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature forecast",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "weather",
     "query": "SELECT last(\"temperature\") FROM \"weather\" WHERE $timeFilter GROUP BY time($interval) ",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "Temperature forecast" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rain for the next 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "alias": "Rain",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "rain" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Indoor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_listener_v2",
     "query": "SELECT (mean(\"tempinf\")-32) * 5/9 FROM \"http_listener_v2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "tempinf" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Outdoor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_listener_v2",
     "query": "SELECT (mean(\"temp1f\")-32)*5/9 FROM \"http_listener_v2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp1f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_listener_v2",
     "select": [
      [
       { "params": [ "baromrelin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}