{
 "title": "Watering",
 "time": { "from": "now-15d", "to": "now" },
 "panels": [
  {
   "title": "Planter Last Watered",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_listener_v2",
     "query": "SELECT derivative(mean(\"soilmoisture1\"),10s) AS \"Planter\" FROM \"http_listener_v2\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "soilmoisture1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Planter" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bonsai Last Watered",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_listener_v2",
     "query": "SELECT derivative(mean(\"soilmoisture2\"),10s) AS \"Bonsai\" FROM \"http_listener_v2\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "soilmoisture1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Planter" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Soil Moisture",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_listener_v2",
     "select": [
      [
       { "params": [ "soilmoisture1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Planter" ], "type": "alias" }
      ],
      [
       { "params": [ "soilmoisture2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bonsai" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_listener_v2",
     "query": "SELECT derivative(mean(\"soilmoisture1\"), 10s) FROM \"http_listener_v2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "soilmoisture1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(\"soilmoisture2\"), 10s) FROM \"http_listener_v2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}